# Use the official MongoDB image as the base image
FROM mongo:latest

# Set environment variables for MongoDB root username and password
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=secret
# Expose the port on which the Flask application will run
EXPOSE 8500
